
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StarsBackground } from "./Components/StarsBackground";
import { ShootingStars } from "./Components/StarsShoot";
import Navbara from "./Components/Navbara";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">

      <title>Karim Zaafrani</title>
      <link rel="icon" href="identity_picture.jpeg" />
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="overflow-x-hidden h-full w-full rounded-md bg-neutral-900 flex flex-col items-center justify-center relative p-0 m-0">
          
        <ShootingStars className="z-0 h-screen w-screen"/>
          <StarsBackground  className="z-0 h-screen w-screen"/>
          <Navbara />
           <div className="z-40">  {children}</div>
            
        </div>
      </body>
      
    </html>
  );
}
